trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  acrName: acrappsadrian
  imageName: test-page
  resourceGroup: rg-test-page
  containerAppName: test-page
  tag: $(Build.BuildId)

stages:

# =========================
# BUILD + PUSH (ACR BUILD)
# =========================
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push to ACR
    steps:

    - task: AzureCLI@2
      displayName: Build and Push Image to ACR
      inputs:
        azureSubscription: 'appDeployConnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "=== DEBUG ==="
          echo "Directorio actual:"
          pwd

          echo "Archivos en repo:"
          ls -la

          echo "Buscando dockerfile..."
          find . -name "dockerfile"

          echo "Verificando ACR..."
          az acr list -o table

          echo "Construyendo imagen..."
          az acr build \
            --registry $(acrName) \
            --image $(imageName):$(tag) \
            --file dockerfile \
            .

# =========================
# DEPLOY
# =========================
- stage: Deploy
  displayName: Deploy to Container App
  dependsOn: Build
  jobs:
  - job: DeployApp
    displayName: Deploy App
    steps:

    - task: AzureCLI@2
      displayName: Update Container App
      inputs:
        azureSubscription: 'appDeployConnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Desplegando nueva versión..."
          az containerapp update \
            --name $(containerAppName) \
            --resource-group $(resourceGroup) \
            --image $(acrName).azurecr.io/$(imageName):$(tag)